### ISSUE TITLE
Act like an authentication module, initiate proxy session if login succeeded on backend

### ISSUE THREAD

**Issue by vdudouyt** [Castaglia/proftpd-mod_proxy#127]
Is it possible to make proftpd-mod_proxy working in the following way?

1. Each login & pass supplied in command connection is getting tried on backend
2. If succeeded, then a reverse proxy session is getting initiated
3. Otherwise the control is getting passed to the next authentication module.

**Comment by kdesjard** [comment]
I have a similar request.  Would it be possible to connect to the proxy host (instead of the destination host)  if the @ is not found in the username?   

Ie:

If a client connects to SERVER_A with username "username", the client simply connects to that instance (SERVER_A) of proftpd (mod_proxy just returns and passes auth to next auth module as above)

If a client connects to SERVER_A with username "username@SERVER_B", the client is proxied to SERVER_B

Thanks, Kris.

**Comment by Castaglia** [comment]
No, this doesn't sound like something that `mod_proxy` should do.

In order to try the provided credentials against a backend server, `mod_proxy` would already have to make a TCP connection, "initiating a reverse proxy session" anyway.

And this feature request sounds more like an auth module, which should be done separately from `mod_proxy`.
