### ISSUE TITLE
RoundRobin connect policy always picks first entry in a pool

### ISSUE THREAD

**Issue by cardacane** [Castaglia/proftpd-mod_proxy#132]
Hello Everyone.
I'm new about mod_proxy, I successfully compiled and configured the module but I missing something about RoundRobin.
```
LoadModule mod_proxy.c
<IfModule mod_proxy.c>
    ProxyEngine on
    ProxyLog /var/log/proxy.log
    ProxyTables /tmp/proxy

    ProxyRole reverse
    ProxyReverseConnectPolicy Random
    #ProxyReverseConnectPolicy RoundRobin
    ProxyReverseServers ftp://172.30.138.228:2121 ftp://172.30.138.229:2121
</IfModule>
```
In this config the mod_proxy take always the first entry in the ProxyReverseServers Using Random Policy I can use both ftp server.
```
/opt/proftpd/sbin/proftpd -v
ProFTPD Version 1.3.7rc1
```
any help?

**Comment by Castaglia** [comment]
I've been working on reproducing this locally.  (Note that the issue _title_ mentioned `RoundRobin`, but your configuration uses `Random` as the policy.)

With only 2 servers to choose from randomly, there is no _guarantee_ that the second server will be select first.  The `mod_proxy` module uses the [`random(3)`](https://linux.die.net/man/3/random) where available (and [`rand(3)`](https://linux.die.net/man/3/rand) otherwise); these are pseudo-random number generators.

Now for the `RoundRobin` policy, it _will_ currently always start with the first server.  As this caught you off-guard, are you thinking that `RoundRobin` should first pick a random server, and then round-robin from there?

**Comment by Castaglia** [comment]
Ah, I see what you're getting at.  For the first client that connects (successfully) to `mod_proxy`, it should get the first server.  But the _next_ client that connects to `mod_proxy` should go to the second server, using `RoundRobin`.  Yes.

**Comment by Castaglia** [comment]
This should now be fixed in master.   Thanks!
