### ISSUE TITLE
Trouble building/installing mod_proxy from zip

### ISSUE THREAD

**Issue by hacor** [Castaglia/proftpd-mod_proxy#81]
Hello again,

I hope you don't bother with another question on mod_proxy. For a few days I've been trying to download and build ProFTPd with the mod_proxy plugin. I hope someone has a hint, because I think it is a very stupid mistake I'm overseeing.

I have a clean ubuntu:14.04 docker container and then run the following steps:

`# apt-get update &&
apt-get install wget build-essentials libssl-dev sqlite3 libsqlite3-dev unzip`

Then I download the 1.3.6-rc2 (the latest release of ProFTPd) and download mod_proxy from Github
`# wget ftp://ftp.proftpd.org/distrib/source/proftpd-1.3.6rc2.tar.gz`
`# wget https://github.com/Castaglia/proftpd-mod_proxy/archive/master.zip`

After extracting I go into the /usr/local/src/proftpd-1.3.6rc2/contrib directory and unzip the mod_proxy zipfile
`# cd /usr/local/src/proftpd-1.3.6rc2/contrib && unzip /master.zip -d .`

The previous command creates a new subdirectory inside the contrib dir. Do I need to copy all the contents of the subdir to contrib itself? I tried both but everything fails.
I noticed that I first need to run ./configure inside the mod_proxy directory to create the `mod_proxy.h` file.

The configure command I'm using is this:
`# ./configure --with-includes=/usr/include/openssl:/usr/include:/usr/local/src/proftpd-1.3.6rc2/contrib:/usr/local/src/proftpd-1.3.6rc2/contrib/include --with-libraries=/usr/lib/ssl:/usr/lib/x86_64-linux-gnu/:/usr/local/src/proftpd-1.3.6rc2/contrib/lib --enable-openssl --with-modules=mod_sql:mod_sql_sqlite:mod_tls:mod_sftp:mod_proxy --enable-dso`

I always run into the same problems:
- Cannot find `mod_proxy.c` (this is solved by copying the contents of mod_proxy Github straight into contrib)
- A lot of undefined reference mod_proxy_.... errors during the linking process

If I remove mod_proxy form the configure line it builds perfectly.
I hope I can contribute to ProFTPd by creating a Dockerfile/container and the Docker hub to help others use/install ProFTPd and mod_proxy.

I'm sorry for this probably very noob question.
Hope someone can help.

Best regards

Hacor

**Comment by Castaglia** [comment]
I tend to use the `.tar.gz` files, honestly, not the `.zip` files; when I get a chance, I'll try building from a `.zip` file.

In the mean time, what you want to see in the `proftpd-1.3.6rc2/contrib/` directory, _before_ running the `./configure` command, is a directory called `mod_proxy/`, _i.e._ `proftpd-1.3.6rc2/contrib/mod_proxy/`.  That `mod_proxy/` directory should contain `mod_proxy.c` and all of the other mod_proxy-related `.c` and `.h` files.

**Comment by hacor** [comment]
That's the trick!
I needed to rename the folder that was automatically created by the unzip function from `proftpd-mod_proxy-master` to `mod_proxy`. The first directory name was automatically generated by Github.

Are you interested in a step by step guide to install & compile ProFTPd including mod_proxy? I've written everything down!

Best regards,
You made my day!

Hacor

**Comment by Castaglia** [comment]
I'd love to have a step-by-step guide for building/installing ProFTPD with mod_proxy!  If you add your steps to this issue, I'll fold them into the `mod_proxy.html` docs.  Thanks!

**Comment by hacor** [comment]
As promised, here is the step by step guide to compile ProFTPd with mod_proxy! I hope soon to provide a working Dockerfile and Docker image for out of the box usage on all systems! After that I'll try to provide a working example concerning my particular situation. 

Thanks in advance for all the assistance!

### Tutorial on how to install ProFTPd with mod_proxy

All commands underneath are tested on an Ubuntu 14.04 system. Some library/include locations may differ from your personal Unix system. Read the docs of your personal OS to find those locations.

First update your system and install the necessary packages

```
 # apt-get update
 # apt-get install wget build-essential libssl-dev sqlite3 libsqlite3-dev git
```
Next steps are to create the necessary directories and download and untar the source codes of ProFTPd and mod_proxy.
`# mkdir -p /usr/local/src && cd /usr/local/src`

Download ProFTPd source code (look on www.proftpd.org for the latest release)
` # wget ftp://ftp.proftpd.org/distrib/source/proftpd-1.3.6rc2.tar.gz`

Download mod_proxy from github
` # git clone https://github.com/Castaglia/proftpd-mod_proxy.git`

Untar the source code from ProFTPd
` # tar -xvf proftpd-1.3.6rc2.tar.gz`

Enter the contrib directory to copy the mod_proxy source code
` # cd proftpd-1.3.6rc2/contrib/`

Copy the contents of the cloned Github repository to a newly created directory called `mod_proxy`
```
 # mkdir mod_proxy && cd mod_proxy
 # cp -rf ../../../proftpd-mod_proxy/* .
```

Now all the files are in place and we can configure ProFTPd to build the necessary modules. For this tutorial the following modules were selected (mod_sql is necessary to succesfully build mod_proxy, all the rest are extras):
- mod_proxy
- mod_sql
- mod_sql_sqlite
- mod_tls
- mod_sftp

You can change the `configure` as you please, be sure to check the directories and change accordingly to your system.
```
 # cd ../../
 # ./configure --with-includes=/usr/include/openssl:/usr/include:/usr/local/src/proftpd-1.3.6rc2/contrib:/usr/local/src/proftpd-1.3.6rc2/contrib/mod_proxy/include --with-libraries=/usr/lib/ssl:/usr/lib/x86_64-linux-gnu/:/usr/local/src/proftpd-1.3.6rc2/contrib/mod_proxy/lib --enable-openssl --with-modules=mod_sql:mod_sql_sqlite:mod_tls:mod_sftp:mod_proxy --enable-dso
````

Ready to build! How exciting...
Start the make command
` # make && make install`

You are now ready to roll, you can check which modules are installed by invoking the `proftpd -l` command. In the situation of this tutorial the result of the previous command is:

> Compiled-in modules:
  mod_core.c
  mod_xfer.c
  mod_rlimit.c
  mod_auth_unix.c
  mod_auth_file.c
  mod_auth.c
  mod_ls.c
  mod_log.c
  mod_site.c
  mod_delay.c
  mod_facts.c
  mod_dso.c
  mod_ident.c
  mod_sql.c
  mod_sql_sqlite.c
  mod_tls.c
  mod_sftp.c
  mod_proxy.c
  mod_cap.c

**Comment by pwFoo** [comment]
Because it was build in a ubuntu container. Any plans to build images with installed proftpd +mod_proxy? Or is there an image available?

**Comment by Castaglia** [comment]
The ProFTPD Project itself is not really in the habit of providing images or packages, Docker or otherwise.  You might find other folks who have built/provided images on their own, though, for community use!

**Comment by shakenfr** [comment]
hello,
I follow the tuto (and adapt rc2 by rc4 release)
I have this error 👍 ProFTPD 1.3.6rc5 or later required    but rc5 is not released ??  any idea to install mod-proxy well?

gcc  -DHAVE_CONFIG_H  -DLINUX  -I. -I./include -I../.. -I../../include -I/usr/local/src/proftpd-1.3.6rc4/contrib/mod_proxy/include -I/usr/local/src/proftpd-1.3.6rc4/contrib -I/usr/include -I/usr/include/openssl -g2 -O2 -Wall -fno-omit-frame-pointer -c mod_proxy.c -o mod_proxy.o
In file included from mod_proxy.c:29:0:
mod_proxy.h:63:3: error: #error "ProFTPD 1.3.6rc5 or later required"
 # error "ProFTPD 1.3.6rc5 or later required"
   ^
mod_proxy.c: In function ‘proxy_data_prepare_conns’:
mod_proxy.c:1902:13: warning: implicit declaration of function ‘pr_netaddr_v4tov6’ [-Wimplicit-function-declaration]
             new_addr = pr_netaddr_v4tov6(cmd->pool, local_addr);
             ^
mod_proxy.c:1902:22: warning: assignment makes pointer from integer without a cast
             new_addr = pr_netaddr_v4tov6(cmd->pool, local_addr);
                      ^
Makefile:63: recipe for target 'mod_proxy.o' failed
make[2]: *** [mod_proxy.o] Error 1
make[2]: Leaving directory '/usr/local/src/proftpd-1.3.6rc4/contrib/mod_proxy'
Makefile:47: recipe for target 'static' failed
make[1]: *** [static] Error 2
make[1]: Leaving directory '/usr/local/src/proftpd-1.3.6rc4/modules'
Makefile:39: recipe for target 'modules' failed
make: *** [modules] Error 2

**Comment by ws0w** [comment]
I just edit the line in mod_proxy.h:

#if PROFTPD_VERSION_NUMBER < 0x0001030605

and change the number to match the proftpd version I'm compiling.

**Comment by shakenfr** [comment]
hello,  

I change the version and now I have this error

gcc  -DHAVE_CONFIG_H  -DLINUX  -I. -I./include -I../.. -I../../include -I/usr/local/src/proftpd-1.3.6rc4/contrib/mod_proxy/include -I/usr/local/src/proftpd-1.3.6rc4/contrib -I/usr/include -I/usr/include/openssl -g2 -O2 -Wall -fno-omit-frame-pointer -c lib/proxy/netio.c -o lib/proxy/netio.o
gcc  -DHAVE_CONFIG_H  -DLINUX  -I. -I./include -I../.. -I../../include -I/usr/local/src/proftpd-1.3.6rc4/contrib/mod_proxy/include -I/usr/local/src/proftpd-1.3.6rc4/contrib -I/usr/include -I/usr/include/openssl -g2 -O2 -Wall -fno-omit-frame-pointer -c lib/proxy/inet.c -o lib/proxy/inet.o
gcc  -DHAVE_CONFIG_H  -DLINUX  -I. -I./include -I../.. -I../../include -I/usr/local/src/proftpd-1.3.6rc4/contrib/mod_proxy/include -I/usr/local/src/proftpd-1.3.6rc4/contrib -I/usr/include -I/usr/include/openssl -g2 -O2 -Wall -fno-omit-frame-pointer -c lib/proxy/tls.c -o lib/proxy/tls.o
gcc  -DHAVE_CONFIG_H  -DLINUX  -I. -I./include -I../.. -I../../include -I/usr/local/src/proftpd-1.3.6rc4/contrib/mod_proxy/include -I/usr/local/src/proftpd-1.3.6rc4/contrib -I/usr/include -I/usr/include/openssl -g2 -O2 -Wall -fno-omit-frame-pointer -c lib/proxy/tls/redis.c -o lib/proxy/tls/redis.o
lib/proxy/tls/redis.c:27:19: fatal error: redis.h: No such file or directory
 #include "redis.h"
                   ^
compilation terminated.
Makefile:63: recipe for target 'lib/proxy/tls/redis.o' failed
make[2]: *** [lib/proxy/tls/redis.o] Error 1
make[2]: Leaving directory '/usr/local/src/proftpd-1.3.6rc4/contrib/mod_proxy'
Makefile:47: recipe for target 'static' failed
make[1]: *** [static] Error 2
make[1]: Leaving directory '/usr/local/src/proftpd-1.3.6rc4/modules'
Makefile:39: recipe for target 'modules' failed
make: *** [modules] Error 2
root@proxmox1:/usr/local/src/proftpd-1.3.6rc4# find . -name "redis.h"
./contrib/mod_proxy/include/proxy/reverse/redis.h
./contrib/mod_proxy/include/proxy/tls/redis.h


Have you a already  compiled version for : Linux proxmox1 4.4.59-1-pve #1 SMP PVE 4.4.59-87 (Tue, 25 Apr 2017 09:01:58 +0200) x86_64 GNU/Linux
debian ???

best
bruno

**Comment by ws0w** [comment]
Unfortunately, I use profited on AIX so I can't help with binaries.

It seems that mod_proxy has changed significantly since the last time I compiled it.

**Comment by Castaglia** [comment]
The `mod_proxy` code assumes that you are using the latest ProFTPD release - 1.3.6 stable, in this case.  Hence the check in the header:

    #if PROFTPD_VERSION_NUMBER < 0x0001030605

that you changed.  That check is there _for a reason_ -- it's there to tell you that you cannot build the code against earlier versions of ProFTPD, due to API and functionality changes.  As you are discovering.

If you wish to use the latest `mod_proxy`, you will need to use the ProFTPD 1.3.6 release.

**Comment by shakenfr** [comment]
works well now with 1.3.6 stable !!! thanks friends
best
bruno

**Comment by shakenfr** [comment]
the compilation now works well
 here is my config file

#
# /etc/proftpd/proftpd.conf -- This is a basic ProFTPD configuration file.
# To really apply changes, reload proftpd after modifications, if
# it runs in daemon mode. It is not required in inetd/xinetd mode.
#

# Includes DSO modules
#Include /etc/proftpd/modules.conf
ProxyEngine On
# Set off to disable IPv6 support which is annoying on IPv4 only boxes.
UseIPv6                         on
# If set on you can experience a longer connection delay in many cases.
IdentLookups                    off

ServerName                      "Debian"
ServerType                      standalone
DeferWelcome                    off

MultilineRFC2228                on
DefaultServer                   on
ShowSymlinks                    on

TimeoutNoTransfer               600
TimeoutStalled                  600
TimeoutIdle                     1200

DisplayLogin                    welcome.msg
DisplayChdir                    .message true
ListOptions                     "-l"

DenyFilter                      \*.*/

# Use this to jail all users in their homes
# DefaultRoot                   ~

# Users require a valid shell listed in /etc/shells to login.
# Use this directive to release that constrain.
# RequireValidShell             off

# Port 21 is the standard FTP port.
Port                            21
PassivePorts                  49152 65534

# If your host was NATted, this option is useful in order to
# allow passive tranfers to work. You have to use your public
# address and opening the passive ports used on your firewall as well.
# MasqueradeAddress             1.2.3.4

# This is useful for masquerading address with dynamic IPs:
# refresh any configured MasqueradeAddress directives every 8 hours
<IfModule mod_dynmasq.c>
# DynMasqRefresh 28800
</IfModule>

# To prevent DoS attacks, set the maximum number of child processes
# to 30.  If you need to allow more than 30 concurrent connections
# at once, simply increase this value.  Note that this ONLY works
# in standalone mode, in inetd mode you should use an inetd server
# that allows you to limit maximum number of processes per service
# (such as xinetd)
MaxInstances                    30

# Set the user and group that the server normally runs at.
User                            proftpd
Group                           nogroup

# Umask 022 is a good standard umask to prevent new files and dirs
# (second parm) from being group and world writable.
Umask                           022  022
# Normally, we want files to be overwriteable.
AllowOverwrite                  on

# Uncomment this if you are using NIS or LDAP via NSS to retrieve passwords:
# PersistentPasswd              off

# This is required to use both PAM-based authentication and local passwords
# AuthOrder                     mod_auth_pam.c* mod_auth_unix.c

# Be warned: use of this directive impacts CPU average load!
# Uncomment this if you like to see progress and transfer rate with ftpwho
# in downloads. That is not needed for uploads rates.
#
# UseSendFile                   off

TransferLog /var/log/proftpd/xferlog
SystemLog   /var/log/proftpd/proftpd.log

# Logging onto /var/log/lastlog is enabled but set to off by default
#UseLastlog on

# In order to keep log file dates consistent after chroot, use timezone info
# from /etc/localtime.  If this is not set, and proftpd is configured to
# chroot (e.g. DefaultRoot or <Anonymous>), it will use the non-daylight
# savings timezone regardless of whether DST is in effect.
#SetEnv TZ :/etc/localtime

<IfModule mod_quotatab.c>
QuotaEngine off
</IfModule>

<IfModule mod_ratio.c>
Ratios off
</IfModule>


# Delay engine reduces impact of the so-called Timing Attack described in
# http://www.securityfocus.com/bid/11430/discuss
# It is on by default.
<IfModule mod_delay.c>
DelayEngine on
</IfModule>

<IfModule mod_ctrls.c>
ControlsEngine        off
ControlsMaxClients    2
ControlsLog           /var/log/proftpd/controls.log
ControlsInterval      5
ControlsSocket        /var/run/proftpd/proftpd.sock
</IfModule>
ProxyLog /var/log/proftpd/proxy.log
# Include other custom configuration files
<IfModule mod_proxy.c>
<VirtualHost www.domain.fr>
        ProxyEngine on
        ProxyLog /var/log/proftpd/proxy.log
        ProxyForwardTo ftp://192.168.10.12:21
</VirtualHost>
<VirtualHost preprod.domain.fr>
        ProxyEngine on
        ProxyLog /var/log/proftpd/proxy.log
        ProxyForwardTo ftp://192.168.10.13:21
</VirtualHost>
</IfModule>
Include /etc/proftpd/conf.d/


when I try to connect on ftp It doesn(t word,I have no log . Is my config correct ??

have you an exemple of config file for proxy mod?
